
export type ToolType = 
  | 'cursor' 
  | 'trendline' 
  | 'horizontal_line' 
  | 'ray' 
  | 'vertical_line' 
  | 'cross_line' 
  | 'brush' 
  | 'eraser' 
  | 'measure' 
  | 'zoom' 
  | 'magnet' 
  | 'lock' 
  | 'hide' 
  | 'clear_drawings' 
  | 'date_range'
  | 'long_position'
  | 'short_position'
  // Added missing tool types used in Sidebar and TrendLineTool components
  | 'info_line'
  | 'extended_line'
  | 'trend_angle'
  | 'horizontal_ray'
  | 'fib'
  | 'fib_fan'
  | 'shapes'
  | 'text'
  | 'patterns'
  | 'elliott'
  | 'cycles'
  | 'info'
  | 'icons'
  | 'stay_in_mode'
  | 'rectangle'
  | 'projection'
  | 'anchored_vwap'
  | null;
